// Server-only data module
export interface Surah {
  id: number;
  name: string; // English/latin name
  arabicName: string;
  verses: number;
  duration: string; // "mm:ss" or "h:mm:ss"
  audioUrl?: string; // e.g. "/surahs/001.mp3"
}

export const quranData = {
  sheikhName: "الشيخ أحمد سعيد نصر",
  rawayah: "حفص عن عاصم",
  sheikhImage: "/images/shiekh.png",
  coverImage: "/images/cover.png",
  surahs: [
    {
      id: 1,
      name: "Al-Fatihah",
      arabicName: "الفاتحة",
      verses: 7,
      duration: "0:51",
      audioUrl: "/surah/001.mp3",
    },
    {
      id: 2,
      name: "Al-Baqarah",
      arabicName: "البقرة",
      verses: 286,
      duration: "2:30:45",
      audioUrl: "/surah/002.mp3",
    },
    {
      id: 3,
      name: "Aal-E-Imran",
      arabicName: "آل عمران",
      verses: 200,
      duration: "1:45:20",
      audioUrl: "/surah/003.mp3",
    },
    {
      id: 4,
      name: "An-Nisa’",
      arabicName: "النساء",
      verses: 176,
      duration: "1:21:10",
      audioUrl: "/surah/004.mp3",
    },
    {
      id: 5,
      name: "Al-Ma’idah",
      arabicName: "المائدة",
      verses: 120,
      duration: "0:55:00",
      audioUrl: "/surah/005.mp3",
    },
    {
      id: 6,
      name: "Al-An'am",
      arabicName: "الأنعام",
      verses: 165,
      duration: "01:00:56",
      audioUrl: "/surah/006.mp3",
    },
    {
      id: 7,
      name: "Al-A'raf",
      arabicName: "الأعراف",
      verses: 206,
      duration: "01:10:03",
      audioUrl: "/surah/007.mp3",
    },
    {
      id: 8,
      name: "Al-Anfal",
      arabicName: "الأنفال",
      verses: 75,
      duration: "0:26:04",
      audioUrl: "/surah/008.mp3",
    },
    {
      id: 9,
      name: "At-Tawbah",
      arabicName: "التوبة",
      verses: 129,
      duration: "0:53:03",
      audioUrl: "/surah/009.mp3",
    },
    {
      id: 10,
      name: "Yunus",
      arabicName: "يونس",
      verses: 109,
      duration: "0:37:16",
      audioUrl: "/surah/010.mp3",
    },
    {
      id: 11,
      name: "Hud",
      arabicName: "هود",
      verses: 123,
      duration: "0:38:54",
      audioUrl: "/surah/011.mp3",
    },
    {
      id: 12,
      name: "Yusuf",
      arabicName: "يوسف",
      verses: 111,
      duration: "0:34:33",
      audioUrl: "/surah/012.mp3",
    },
    {
      id: 13,
      name: "Ar-Ra'd",
      arabicName: "الرعد",
      verses: 43,
      duration: "0:16:56",
      audioUrl: "/surah/013.mp3",
    },
    {
      id: 14,
      name: "Ibrahim",
      arabicName: "إبراهيم",
      verses: 52,
      duration: "0:16:53",
      audioUrl: "/surah/014.mp3",
    },
    {
      id: 15,
      name: "Al-Hijr",
      arabicName: "الحجر",
      verses: 99,
      duration: "0:14:38",
      audioUrl: "/surah/015.mp3",
    },
    {
      id: 16,
      name: "An-Nahl",
      arabicName: "النحل",
      verses: 128,
      duration: "0:38:04",
      audioUrl: "/surah/016.mp3",
    },
    {
      id: 17,
      name: "Al-Isra",
      arabicName: "الإسراء",
      verses: 111,
      duration: "0:32:57",
      audioUrl: "/surah/017.mp3",
    },
    {
      id: 18,
      name: "Al-Kahf",
      arabicName: "الكهف",
      verses: 110,
      duration: "0:31:07",
      audioUrl: "/surah/018.mp3",
    },
    {
      id: 19,
      name: "Maryam",
      arabicName: "مريم",
      verses: 98,
      duration: "0:20:32",
      audioUrl: "/surah/019.mp3",
    },
    {
      id: 20,
      name: "Ta-Ha",
      arabicName: "طه",
      verses: 135,
      duration: "0:27:03",
      audioUrl: "/surah/020.mp3",
    },
    {
      id: 21,
      name: "Al-Anbiya",
      arabicName: "الأنبياء",
      verses: 112,
      duration: "0:25:19",
      audioUrl: "/surah/021.mp3",
    },
    {
      id: 22,
      name: "Al-Hajj",
      arabicName: "الحج",
      verses: 78,
      duration: "0:25:23",
      audioUrl: "/surah/022.mp3",
    },
    {
      id: 23,
      name: "Al-Mu'minun",
      arabicName: "المؤمنون",
      verses: 118,
      duration: "0:23:09",
      audioUrl: "/surah/023.mp3",
    },
    {
      id: 24,
      name: "An-Nur",
      arabicName: "النور",
      verses: 64,
      duration: "0:26:58",
      audioUrl: "/surah/024.mp3",
    },
    {
      id: 25,
      name: "Al-Furqan",
      arabicName: "الفرقان",
      verses: 77,
      duration: "0:18:51",
      audioUrl: "/surah/025.mp3",
    },
    {
      id: 26,
      name: "Ash-Shu’ara’",
      arabicName: "الشعراء",
      verses: 227,
      duration: "0:27:52",
      audioUrl: "/surah/026.mp3",
    },
    {
      id: 27,
      name: "An-Naml",
      arabicName: "النمل",
      verses: 93,
      duration: "0:23:15",
      audioUrl: "/surah/027.mp3",
    },
    {
      id: 28,
      name: "Al-Qasas",
      arabicName: "القصص",
      verses: 88,
      duration: "0:28:20",
      audioUrl: "/surah/028.mp3",
    },
    {
      id: 29,
      name: "Al-Ankabut",
      arabicName: "العنكبوت",
      verses: 69,
      duration: "0:20:50",
      audioUrl: "/surah/029.mp3",
    },
    {
      id: 30,
      name: "Ar-Rum",
      arabicName: "الروم",
      verses: 60,
      duration: "0:16:24",
      audioUrl: "/surah/030.mp3",
    },
    {
      id: 31,
      name: "Luqman",
      arabicName: "لقمان",
      verses: 45,
      duration: "0:10:16",
      audioUrl: "/surah/031.mp3",
    },
    {
      id: 32,
      name: "As-Sajda",
      arabicName: "السجدة",
      verses: 30,
      duration: "0:07:22",
      audioUrl: "/surah/032.mp3",
    },
    {
      id: 33,
      name: "Al-Ahzab",
      arabicName: "الاحزاب",
      verses: 73,
      duration: "0:26:14",
      audioUrl: "/surah/033.mp3",
    },
    {
      id: 34,
      name: "Saba’",
      arabicName: "سبأ",
      verses: 54,
      duration: "0:16:48",
      audioUrl: "/surah/034.mp3",
    },
    {
      id: 35,
      name: "Fatir",
      arabicName: "فاطر",
      verses: 45,
      duration: "0:15:22",
      audioUrl: "/surah/035.mp3",
    },
    {
      id: 36,
      name: "Ya-Sin",
      arabicName: "يس",
      verses: 83,
      duration: "0:14:58",
      audioUrl: "/surah/036.mp3",
    },
    {
      id: 37,
      name: "As-Saffat",
      arabicName: "الصافات",
      verses: 182,
      duration: "0:19:04",
      audioUrl: "/surah/037.mp3",
    },
    {
      id: 38,
      name: "Sad",
      arabicName: "ص",
      verses: 88,
      duration: "0:15:04",
      audioUrl: "/surah/038.mp3",
    },
    {
      id: 39,
      name: "Az-Zumar",
      arabicName: "الزمر",
      verses: 75,
      duration: "0:22:34",
      audioUrl: "/surah/039.mp3",
    },
    {
      id: 40,
      name: "Ghafir",
      arabicName: "غافر",
      verses: 85,
      duration: "0:23:17",
      audioUrl: "/surah/040.mp3",
    },
    {
      id: 41,
      name: "Fussilat",
      arabicName: "فصلت",
      verses: 54,
      duration: "0:15:48",
      audioUrl: "/surah/041.mp3",
    },
    {
      id: 42,
      name: "Ash-Shura",
      arabicName: "الشورى",
      verses: 53,
      duration: "0:17:21",
      audioUrl: "/surah/042.mp3",
    },
    {
      id: 43,
      name: "Az-Zukhruf",
      arabicName: "الزخرف",
      verses: 89,
      duration: "0:17:46",
      audioUrl: "/surah/043.mp3",
    },
    {
      id: 44,
      name: "Ad-Dukhan",
      arabicName: "الدخان",
      verses: 59,
      duration: "0:07:25",
      audioUrl: "/surah/044.mp3",
    },
    {
      id: 45,
      name: "Al-Jathiyah",
      arabicName: "الجاثية",
      verses: 37,
      duration: "0:09:19",
      audioUrl: "/surah/045.mp3",
    },
    {
      id: 46,
      name: "Al-Ahqaf",
      arabicName: "الأحقاف",
      verses: 35,
      duration: "0:14:04",
      audioUrl: "/surah/046.mp3",
    },
    {
      id: 47,
      name: "Muhammad",
      arabicName: "محمد",
      verses: 38,
      duration: "0:11:27",
      audioUrl: "/surah/047.mp3",
    },
    {
      id: 48,
      name: "Al-Fath",
      arabicName: "الفتح",
      verses: 29,
      duration: "0:11:17",
      audioUrl: "/surah/048.mp3",
    },
    {
      id: 49,
      name: "Al-Hujurat",
      arabicName: "الحجرات",
      verses: 18,
      duration: "0:06:52",
      audioUrl: "/surah/049.mp3",
    },
    {
      id: 50,
      name: "Qaf",
      arabicName: "ق",
      verses: 45,
      duration: "0:07:31",
      audioUrl: "/surah/050.mp3",
    },
    {
      id: 51,
      name: "Adh-Dhariyat",
      arabicName: "الذاريات",
      verses: 60,
      duration: "0:07:51",
      audioUrl: "/surah/051.mp3",
    },
    {
      id: 52,
      name: "At-Tur",
      arabicName: "الطور",
      verses: 49,
      duration: "0:06:58",
      audioUrl: "/surah/052.mp3",
    },
    {
      id: 53,
      name: "An-Najm",
      arabicName: "النجم",
      verses: 62,
      duration: "0:07:01",
      audioUrl: "/surah/053.mp3",
    },
    {
      id: 54,
      name: "Al-Qamar",
      arabicName: "القمر",
      verses: 55,
      duration: "0:07:13",
      audioUrl: "/surah/054.mp3",
    },
    {
      id: 55,
      name: "Ar-Rahman",
      arabicName: "الرحمن",
      verses: 78,
      duration: "0:09:16",
      audioUrl: "/surah/055.mp3",
    },
    {
      id: 56,
      name: "Al-Waqi'ah",
      arabicName: "الواقعة",
      verses: 96,
      duration: "0:09:11",
      audioUrl: "/surah/056.mp3",
    },
    {
      id: 57,
      name: "Al-Hadid",
      arabicName: "الحديد",
      verses: 29,
      duration: "0:11:42",
      audioUrl: "/surah/057.mp3",
    },
    {
      id: 58,
      name: "Al-Mujadila",
      arabicName: "المجادلة",
      verses: 22,
      duration: "0:10:33",
      audioUrl: "/surah/058.mp3",
    },
    {
      id: 59,
      name: "Al-Hashr",
      arabicName: "الحشر",
      verses: 24,
      duration: "0:10:00",
      audioUrl: "/surah/059.mp3",
    },
    {
      id: 60,
      name: "Al-Mumtahanah",
      arabicName: "الممتحنة",
      verses: 13,
      duration: "0:07:54",
      audioUrl: "/surah/060.mp3",
    },
    {
      id: 61,
      name: "As-Saf",
      arabicName: "الصف",
      verses: 14,
      duration: "0:04:30",
      audioUrl: "/surah/061.mp3",
    },
    {
      id: 62,
      name: "Al-Jumu'ah",
      arabicName: "الجمعة",
      verses: 11,
      duration: "0:03:33",
      audioUrl: "/surah/062.mp3",
    },
    {
      id: 63,
      name: "Al-Munafiqun",
      arabicName: "المنافقون",
      verses: 11,
      duration: "0:03:49",
      audioUrl: "/surah/063.mp3",
    },
    {
      id: 64,
      name: "At-Taghabun",
      arabicName: "التغابن",
      verses: 18,
      duration: "0:04:51",
      audioUrl: "/surah/064.mp3",
    },
    {
      id: 65,
      name: "At-Talaq",
      arabicName: "الطلاق",
      verses: 12,
      duration: "0:06:02",
      audioUrl: "/surah/065.mp3",
    },
    {
      id: 66,
      name: "At-Tahrim",
      arabicName: "التحريم",
      verses: 12,
      duration: "0:05:17",
      audioUrl: "/surah/066.mp3",
    },
    {
      id: 67,
      name: "Al-Mulk",
      arabicName: "الملك",
      verses: 30,
      duration: "0:06:54",
      audioUrl: "/surah/067.mp3",
    },
    {
      id: 68,
      name: "Al-Qalam",
      arabicName: "القلم",
      verses: 52,
      duration: "0:06:52",
      audioUrl: "/surah/068.mp3",
    },
    {
      id: 69,
      name: "Al-Haqqah",
      arabicName: "الحاقة",
      verses: 52,
      duration: "0:06:00",
      audioUrl: "/surah/069.mp3",
    },
    {
      id: 70,
      name: "Al-Ma'arij",
      arabicName: "المعارج",
      verses: 44,
      duration: "0:04:50",
      audioUrl: "/surah/070.mp3",
    },
    {
      id: 71,
      name: "Nuh",
      arabicName: "نوح",
      verses: 28,
      duration: "0:04:49",
      audioUrl: "/surah/071.mp3",
    },
    {
      id: 72,
      name: "Al-Jinn",
      arabicName: "الجن",
      verses: 28,
      duration: "0:05:21",
      audioUrl: "/surah/072.mp3",
    },
    {
      id: 73,
      name: "Al-Muzzammil",
      arabicName: "المزمل",
      verses: 20,
      duration: "0:04:04",
      audioUrl: "/surah/073.mp3",
    },
    {
      id: 74,
      name: "Al-Muddaththir",
      arabicName: "المدثر",
      verses: 56,
      duration: "0:05:25",
      audioUrl: "/surah/074.mp3",
    },
    {
      id: 75,
      name: "Al-Qiyamah",
      arabicName: "القيامة",
      verses: 40,
      duration: "0:03:14",
      audioUrl: "/surah/075.mp3",
    },
    {
      id: 76,
      name: "Al-Insan",
      arabicName: "الإنسان",
      verses: 31,
      duration: "0:05:19",
      audioUrl: "/surah/076.mp3",
    },
    {
      id: 77,
      name: "Al-Mursalat",
      arabicName: "المرسلات",
      verses: 50,
      duration: "0:04:27",
      audioUrl: "/surah/077.mp3",
    },
    {
      id: 78,
      name: "An-Naba",
      arabicName: "النبأ",
      verses: 40,
      duration: "0:04:29",
      audioUrl: "/surah/078.mp3",
    },
    {
      id: 79,
      name: "An-Nazi'at",
      arabicName: "النازعات",
      verses: 46,
      duration: "0:04:06",
      audioUrl: "/surah/079.mp3",
    },
    {
      id: 80,
      name: "Abasa",
      arabicName: "عبس",
      verses: 42,
      duration: "0:03:16",
      audioUrl: "/surah/080.mp3",
    },
    {
      id: 81,
      name: "At-Takwir",
      arabicName: "التكوير",
      verses: 29,
      duration: "0:02:20",
      audioUrl: "/surah/081.mp3",
    },
    {
      id: 82,
      name: "Al-Infitar",
      arabicName: "الانفطار",
      verses: 19,
      duration: "0:01:48",
      audioUrl: "/surah/082.mp3",
    },
    {
      id: 83,
      name: "Al-Mutaffifin",
      arabicName: "المطففين",
      verses: 36,
      duration: "0:03:54",
      audioUrl: "/surah/083.mp3",
    },
    {
      id: 84,
      name: "Al-Inshiqaq",
      arabicName: "الانشقاق",
      verses: 25,
      duration: "0:02:22",
      audioUrl: "/surah/084.mp3",
    },
    {
      id: 85,
      name: "Al-Buruj",
      arabicName: "البروج",
      verses: 22,
      duration: "0:02:08",
      audioUrl: "/surah/085.mp3",
    },
    {
      id: 86,
      name: "At-Tariq",
      arabicName: "الطارق",
      verses: 17,
      duration: "0:01:28",
      audioUrl: "/surah/086.mp3",
    },
    {
      id: 87,
      name: "Al-A'la",
      arabicName: "الأعلى",
      verses: 19,
      duration: "0:01:31",
      audioUrl: "/surah/087.mp3",
    },
    {
      id: 88,
      name: "Al-Ghashiyah",
      arabicName: "الغاشية",
      verses: 26,
      duration: "0:1:59",
      audioUrl: "/surah/088.mp3",
    },
    {
      id: 89,
      name: "Al-Fajr",
      arabicName: "الفجر",
      verses: 30,
      duration: "0:03:01",
      audioUrl: "/surah/089.mp3",
    },
    {
      id: 90,
      name: "Al-Balad",
      arabicName: "البلد",
      verses: 20,
      duration: "0:01:39",
      audioUrl: "/surah/090.mp3",
    },
    {
      id: 91,
      name: "Ash-Shams",
      arabicName: "الشمس",
      verses: 15,
      duration: "0:01:21",
      audioUrl: "/surah/091.mp3",
    },
    {
      id: 92,
      name: "Al-Lail",
      arabicName: "الليل",
      verses: 21,
      duration: "0:01:36",
      audioUrl: "/surah/092.mp3",
    },
    {
      id: 93,
      name: "Ad-Duhaa",
      arabicName: "الضحى",
      verses: 11,
      duration: "0:00:59",
      audioUrl: "/surah/093.mp3",
    },
    {
      id: 94,
      name: "Ash-Sharh",
      arabicName: "الشرح",
      verses: 8,
      duration: "0:00:37",
      audioUrl: "/surah/094.mp3",
    },
    {
      id: 95,
      name: "At-Tin",
      arabicName: "التين",
      verses: 8,
      duration: "0:00:46",
      audioUrl: "/surah/095.mp3",
    },
    {
      id: 96,
      name: "Al-Alaq",
      arabicName: "العلق",
      verses: 19,
      duration: "0:01:26",
      audioUrl: "/surah/096.mp3",
    },
    {
      id: 97,
      name: "Al-Qadr",
      arabicName: "القدر",
      verses: 5,
      duration: "0:00:36",
      audioUrl: "/surah/097.mp3",
    },
    {
      id: 98,
      name: "Al-Bayyina",
      arabicName: "البينة",
      verses: 8,
      duration: "0:01:53",
      audioUrl: "/surah/098.mp3",
    },
    {
      id: 99,
      name: "Az-Zalzalah",
      arabicName: "الزلزلة",
      verses: 8,
      duration: "0:00:49",
      audioUrl: "/surah/099.mp3",
    },
    {
      id: 100,
      name: "Al-Adiyat",
      arabicName: "العاديات",
      verses: 11,
      duration: "0:00:52",
      audioUrl: "/surah/100.mp3",
    },
    {
      id: 101,
      name: "Al-Qari'ah",
      arabicName: "القارعة",
      verses: 11,
      duration: "0:00:48",
      audioUrl: "/surah/101.mp3",
    },
    {
      id: 102,
      name: "At-Takathur",
      arabicName: "التكاثر",
      verses: 8,
      duration: "0:00:43",
      audioUrl: "/surah/102.mp3",
    },
    {
      id: 103,
      name: "Al-Asr",
      arabicName: "العصر",
      verses: 3,
      duration: "0:00:23",
      audioUrl: "/surah/103.mp3",
    },
    {
      id: 104,
      name: "Al-Humazah",
      arabicName: "الهمزة",
      verses: 9,
      duration: "0:00:42",
      audioUrl: "/surah/104.mp3",
    },
    {
      id: 105,
      name: "Al-Fil",
      arabicName: "الفيل",
      verses: 5,
      duration: "0:00:33",
      audioUrl: "/surah/105.mp3",
    },
    {
      id: 106,
      name: "Quraish",
      arabicName: "قريش",
      verses: 4,
      duration: "0:00:30",
      audioUrl: "/surah/106.mp3",
    },
    {
      id: 107,
      name: "Al-Ma'un",
      arabicName: "الماعون",
      verses: 7,
      duration: "0:00:39",
      audioUrl: "/surah/107.mp3",
    },
    {
      id: 108,
      name: "Al-Kawthar",
      arabicName: "الكوثر",
      verses: 3,
      duration: "0:00:17",
      audioUrl: "/surah/108.mp3",
    },
    {
      id: 109,
      name: "Al-Kafiroon",
      arabicName: "الكافرون",
      verses: 6,
      duration: "0:00:32",
      audioUrl: "/surah/109.mp3",
    },
    {
      id: 110,
      name: "An-Nasr",
      arabicName: "النصر",
      verses: 3,
      duration: "0:00:28",
      audioUrl: "/surah/110.mp3",
    },
    {
      id: 111,
      name: "Al-Masad",
      arabicName: "المسد",
      verses: 5,
      duration: "0:00:30",
      audioUrl: "/surah/111.mp3",
    },
    {
      id: 112,
      name: "Al-Ikhlas",
      arabicName: "الإخلاص",
      verses: 4,
      duration: "0:00:18",
      audioUrl: "/surah/112.mp3",
    },
    {
      id: 113,
      name: "Al-Falaq",
      arabicName: "الفلق",
      verses: 5,
      duration: "0:00:28",
      audioUrl: "/surah/113.mp3",
    },
    {
      id: 114,
      name: "An-Nas",
      arabicName: "الناس",
      verses: 6,
      duration: "0:00:38",
      audioUrl: "/surah/114.mp3",
    },

    // ... keep the rest, ensure verses are numbers and audioUrl starts with /surahs
  ] as Surah[],
} as const;

export function getSurahById(id: number): Surah | undefined {
  return quranData.surahs.find((s) => s.id === id);
}
