// Server-only data module
export interface Surah {
  id: number;
  name: string; // English/latin name
  arabicName: string;
  verses: number;
  duration: string; // "mm:ss" or "h:mm:ss"
  audioUrl?: string; // e.g. "/surahs/001.mp3"
}

export const quranData = {
  sheikhName: "الشيخ أحمد سعيد نصر",
  rawayah: "حفص عن عاصم",
  sheikhImage: "/images/shiekh.png",
  coverImage: "/images/cover.png",
  surahs: [
    {
      id: 1,
      name: "Al-Fatihah",
      arabicName: "الفاتحة",
      verses: 7,
      duration: "0:51",
      audioUrl: "/surah/001.mp3",
    },
    {
      id: 2,
      name: "Al-Baqarah",
      arabicName: "البقرة",
      verses: 286,
      duration: "2:30:45",
      audioUrl: "/surah/002.mp3",
    },
    {
      id: 3,
      name: "Aal-E-Imran",
      arabicName: "آل عمران",
      verses: 200,
      duration: "1:45:20",
      audioUrl: "/surah/003.mp3",
    },
    {
      id: 4,
      name: "An-Nisa’",
      arabicName: "النساء",
      verses: 176,
      duration: "1:21:10",
      audioUrl: "/surah/004.mp3",
    },
    {
      id: 5,
      name: "Al-Ma’idah",
      arabicName: "المائدة",
      verses: 120,
      duration: "0:55:00",
      audioUrl : "/surah/005.mp3",
    },
    {
      id: 6,
      name: "Al-An'am",
      arabicName: "الأنعام",
      verses: 165,
      duration: "01:00:56",
      audioUrl: "/surah/006.mp3",
    },
    {
      id: 7,
      name: "Al-A'raf",
      arabicName: "الأعراف",
      verses: 206,
      duration: "01:10:03",
      audioUrl: "/surah/007.mp3",
    },
    {
      id: 8,
      name: "Al-Anfal",
      arabicName: "الأنفال",
      verses: 75,
      duration: "0:26:04",
      audioUrl: "/surah/008.mp3",
    },
    {
      id: 9,
      name: "At-Tawbah",
      arabicName: "التوبة",
      verses: 129,
      duration: "0:53:03",
      audioUrl: "/surah/009.mp3",
    },
        {
      id: 10,
      name: "Yunus",
      arabicName: "يونس",
      verses: 109,
      duration: "0:37:16",
      audioUrl: "/surah/010.mp3",
    },
        {
      id: 11,
      name: "Hud",
      arabicName: "هود",
      verses: 123,
      duration: "0:38:54",
      audioUrl: "/surah/011.mp3",
    },
        {
      id: 12,
      name: "Yusuf",
      arabicName: "يوسف",
      verses: 111,
      duration: "0:34:33",
      audioUrl: "/surah/012.mp3",
    },
        {
      id: 13,
      name: "Ar-Ra'd",
      arabicName: "الرعد",
      verses: 43,
      duration: "0:16:56",
      audioUrl: "/surah/013.mp3",
    },
        {
      id: 14,
      name: "Ibrahim",
      arabicName: "إبراهيم",
      verses: 52,
      duration: "0:16:53",
      audioUrl: "/surah/014.mp3",
    },
        {
      id: 15,
      name: "Al-Hijr",
      arabicName: "الحجر",
      verses: 99,
      duration: "0:14:38",
      audioUrl  : "/surah/015.mp3",
    },
        { id: 16,
      name: "An-Nahl",
      arabicName: "النحل",
      verses: 128,
      duration: "0:38:04",
      audioUrl: "/surah/016.mp3",
    },
        { id: 17,
      name: "Al-Isra",
      arabicName: "الإسراء",
      verses: 111,
      duration: "0:32:57",
      audioUrl: "/surah/017.mp3",
    },
    { id: 18,
      name: "Al-Kahf",
      arabicName: "الكهف",
      verses: 110,
      duration: "0:31:07",
      audioUrl: "/surah/018.mp3",
    },
        { id: 19,
      name: "Maryam",
      arabicName: "مريم",
      verses: 98,
      duration: "0:20:32",
      audioUrl: "/surah/019.mp3",
    },
        { id: 20,
      name: "Ta-Ha",
      arabicName: "طه",
      verses: 135,
      duration: "0:27:03",
      audioUrl: "/surah/020.mp3",
    },
        { id: 21,
      name: "Al-Anbiya",
      arabicName: "الأنبياء",
      verses: 112,
      duration: "0:25:19",
      audioUrl: "/surah/021.mp3",
    },
        { id: 22,
      name: "Al-Hajj",
      arabicName: "الحج",
      verses: 78,
      duration: "0:25:23",
      audioUrl: "/surah/022.mp3",
    },
        { id: 23,
      name: "Al-Mu'minun",
      arabicName: "المؤمنون",
      verses: 118,
      duration: "0:23:09",
      audioUrl: "/surah/023.mp3",
    },
        { id: 24,
      name: "An-Nur",
      arabicName: "النور",
      verses: 64,
      duration: "0:26:58",
      audioUrl: "/surah/024.mp3",
    },
        { id: 25,
      name: "Al-Furqan",
      arabicName: "الفرقان",
      verses: 77,
      duration: "0:18:51",
      audioUrl: "/surah/025.mp3",
    },

    

    // ... keep the rest, ensure verses are numbers and audioUrl starts with /surahs
  ] as Surah[],
} as const;

export function getSurahById(id: number): Surah | undefined {
  return quranData.surahs.find((s) => s.id === id);
}
